import type { Metadata } from "next";
import { Inter } from "@next/font/google";
import "../styles/globals.css";
import { Provider } from "./providers";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className}`}>
        <Toaster />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
